### ISSUE TITLE
It's seemed the RubyGems version (0.16.0) is missing some files in browsers folder.

### ISSUE THREAD

**Issue by cnluzhang** [gshutler/useragent#23]
When I upgrade useragent gem to 0.16.0, I catch the error:
LoadError: cannot load such file -- user_agent/browsers/playstation
...
/Users/Sean/.rvm/gems/ruby-2.2.2@xxx/gems/useragent-0.16.0/lib/user_agent/browsers.rb:12:in `<top (required)>'
...

I found that the browsers.rb is new version which it contains " require 'user_agent/browsers/playstation' ", 
but there is no file named playstation.rb in gem's lib/user_agent/browsers/ folder.

the source is https://rubygems.org.

**Comment by timonv** [comment]
I can confirm they are missing here too.

**Comment by gshutler** [comment]
Sorry, my bad, I'll fix it once I'm back at my desk.

**Comment by gshutler** [comment]
This is fixed in 0.16.1
