### ISSUE TITLE
Unsupported user-agent

### ISSUE THREAD

**Issue by janaz** [gshutler/useragent#31]
I found a request in my app coming from the following user-agent:
`HUAWEI_MT7-TL00_TD/5.0 Android/4.4.2 (Linux; U; Android 4.4.2; zh-cn) Release/01.18.2014 Browser/WAP2.0 (AppleWebKit/537.36) Mobile Safari/537.36 `

The only useful information I was able to retrieve using the gem were:
- browser: HUAWEI_MT7-TL00_TD
- version: 5.0
- mobile?: true

http://www.useragentstring.com/ was able to return more information from that UA string

**Comment by gshutler** [comment]
We should be pulling out more useful information for this browser from 0.16.7

Thanks for the report :100:
