### ISSUE TITLE
Opera browser 28 is reported as version 5.0

### ISSUE THREAD

**Issue by ysbaddaden** [gshutler/useragent#4]
The chromium-based Opera browser is correctly detected, but the reported version is `5.0` from the `Mozilla/5.0` product, instead of the actual version from `OPR/28.0.1750.48`. The actual user-agent string is:

```
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.89 Safari/537.36 OPR/28.0.1750.48
```

**Comment by gshutler** [comment]
Released in 0.13.2

**Comment by gshutler** [comment]
Thanks for the report.

**Comment by ysbaddaden** [comment]
Thanks for the speedy fix and release!

**Comment by gshutler** [comment]
No problem!
