### ISSUE TITLE
Question: are tablets identified as mobile

### ISSUE THREAD

**Issue by sir-dunxalot** [gshutler/useragent#41]
Hi Gary,

Thanks for maintaining this gem! Are tablets identified as `mobile`? I read through the code but it's not clear either way.

Thanks,
Duncan

**Comment by gshutler** [comment]
It's generally defined by the OS, so yes if it is iOS or Android but there could be some ambiguity around Windows-based tablets.

**Comment by sir-dunxalot** [comment]
Great, thanks for the quick response!
