### ISSUE TITLE
Android versions are incorrect

### ISSUE THREAD

**Issue by jargalan** [gshutler/useragent#5]
It always shows up like
->browser: Android 
->version: 4.0
from Android devices. And it is wrong.

in such cases:
Mozilla/5.0 (Linux; U; Android 4.0.3; ko-kr; LG-L160L Build/IML74K) AppleWebkit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
Mozilla/5.0 (Linux; U; Android 4.0.3; de-ch; HTC Sensation Build/IML74K) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
Mozilla/5.0 (Linux; U; Android 2.3; en-us) AppleWebKit/999+ (KHTML, like Gecko) Safari/999.9
Mozilla/5.0 (Linux; U; Android 2.3.5; zh-cn; HTC_IncredibleS_S710e Build/GRJ90) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1
Mozilla/5.0 (Linux; U; Android 2.3.5; en-us; HTC Vision Build/GRI40) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1
Mozilla/5.0 (Linux; U; Android 2.3.4; fr-fr; HTC Desire Build/GRJ22) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1
Mozilla/5.0 (Linux; U; Android 2.3.4; en-us; T-Mobile myTouch 3G Slide Build/GRI40) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1
Mozilla/5.0 (Linux; U; Android 2.3.3; zh-tw; HTC_Pyramid Build/GRI40) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1
Mozilla/5.0 (Linux; U; Android 2.3.3; zh-tw; HTC_Pyramid Build/GRI40) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari
Mozilla/5.0 (Linux; U; Android 2.3.3; zh-tw; HTC Pyramid Build/GRI40) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1
Mozilla/5.0 (Linux; U; Android 2.3.3; ko-kr; LG-LU3000 Build/GRI40) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1
Mozilla/5.0 (Linux; U; Android 2.3.3; en-us; HTC_DesireS_S510e Build/GRI40) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1
Mozilla/5.0 (Linux; U; Android 2.3.3; en-us; HTC_DesireS_S510e Build/GRI40) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile
Mozilla/5.0 (Linux; U; Android 2.3.3; de-de; HTC Desire Build/GRI40) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1
Mozilla/5.0 (Linux; U; Android 2.3.3; de-ch; HTC Desire Build/FRF91) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1
Mozilla/5.0 (Linux; U; Android 2.2; fr-lu; HTC Legend Build/FRF91) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1
Mozilla/5.0 (Linux; U; Android 2.2; en-sa; HTC_DesireHD_A9191 Build/FRF91) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1
Mozilla/5.0 (Linux; U; Android 2.2.1; fr-fr; HTC_DesireZ_A7272 Build/FRG83D) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1
Mozilla/5.0 (Linux; U; Android 2.2.1; en-gb; HTC_DesireZ_A7272 Build/FRG83D) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1
Mozilla/5.0 (Linux; U; Android 2.2.1; en-ca; LG-P505R Build/FRG83) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1

I expected 
browser: Android 
version: 4.0.3
or 
browser: Android 
version: 2.3.3
or 
browser: Android
version: 2.2.1
....
etc

**Comment by gshutler** [comment]
I haven't forgotten about this, just haven't had time to look into it yet. A PR would be more than welcome :smiley_cat:

**Comment by gshutler** [comment]
Had some time to look into this and I'm not sure the version you are expecting is correct. The versions you have specified is the version of Android, this is contained within the `#os` property.

I'm not saying 4.0 is correct, my suspicion is that the WebKit version is likely what we want (534.30, 533.1, etc) as this is more likely to reflect the capability of the device. However, I'm struggling to find anything definitive on the subject.

**Comment by gshutler** [comment]
For my reference, this is probably hitting the [`WebKit` browser](https://github.com/gshutler/useragent/blob/471a5d11f4acc1cfe01569c8f7677374f1aec41d/lib/user_agent/browsers/webkit.rb#L59-60).

**Comment by gshutler** [comment]
Closed by #9

**Comment by j0tunn** [comment]
@gshutler Hi, did you eventually understand what `Version/4.0` actually means in Android Browser User-Agent string?

**Comment by gshutler** [comment]
I couldn't find a definitive source that said that 4.0 was correct or incorrect, but we did get #9 which tidied things up a bit so that Android would be identified as a Webkit browser and have it's information extracted better.

See [the specs](https://github.com/gshutler/useragent/blob/5ea0d33af6cea196b34970f6daa49d1f9a35277a/spec/browsers/webkit_user_agent_spec.rb#L1165-L1203) for an example.

**Comment by j0tunn** [comment]
> I couldn't find a definitive source that said that 4.0 was correct or incorrect

Me too. But if you'll open settings in device - you'll see actual browser version. For example on Android 2.3.7 it looks like this:
![Android 2.3.7](https://yadi.sk/i/gKJTKzf-j7TPd_L.png)

Looks like `Version` field is a `Safari` version, on which Android Browser based. At least http://www.useragentstring.com/index.php says so when you insert Android User Agent string.

> See the specs for an example

That spec is not helpful in fact: `4.0` can be that value from `Version/4.0`. You should probably use some `Android 2.3.3` user agent string instead.
