### ISSUE TITLE
iPad in-app browser not properly detected

### ISSUE THREAD

**Issue by DZittersteyn** [gshutler/useragent#7]
The iPad in-app browser from Feedly (UA string `Mozilla/5.0 (iPad; CPU OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Mobile/12F69`) is not properly recognized:

```
ipad = UserAgent.parse 'Mozilla/5.0 (iPad; CPU OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Mobile/12F69'
=> [#<UserAgent:0x007f8f449c0ce0 @comment=["iPad", "CPU OS 8_3 like Mac OS X"], @product="Mozilla", @version=#<UserAgent::Version 5.0>>,
 #<UserAgent:0x007f8f449c0240 @comment=["KHTML, like Gecko"], @product="AppleWebKit", @version=#<UserAgent::Version 600.1.4>>,
 #<UserAgent:0x007f8f449cb8e8 @comment=nil, @product="Mobile", @version=#<UserAgent::Version 12F69>>]

ipad.version
=> #<UserAgent::Version >
```

I'm not 100% sure if this is an issue with Feedly's in-app browser (it's missing both the `Version/<>` and `Safari/<>` strings), or if this is a bug in useragent. I did some debugging, and there seem to be some weird things going on with the UA parsing:

https://github.com/gshutler/useragent/blob/master/lib/user_agent/operating_systems.rb#L23, where 
`if os =~ /CPU OS\s*([0-9_\.]+)?\slike Mac OS X/` matches the iPad in-app UA. This means that `os` is set by https://github.com/gshutler/useragent/blob/master/lib/user_agent/browsers/webkit.rb#L96 to something that does not match https://github.com/gshutler/useragent/blob/master/lib/user_agent/browsers/webkit.rb#L57, which, if not a bug, is at least a bit smelly

Below a number of UA strings from iPad and iPhone browsers, both in-app (Feedly) and in the Safari app

description | UA
------|------
iPad Feedly in-app | Mozilla/5.0 (iPad; CPU OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Mobile/12F69
iPad Safari | Mozilla/5.0 (iPad; CPU OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12F69 Safari/600.1.4
iPhone Feedly in-app | Mozilla/5.0 (iPhone; CPU iPhone OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Mobile/12F70
iPhone Safari | Mozilla/5.0 (iPhone; CPU iPhone OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12F70 Safari/600.1.4

**Comment by gshutler** [comment]
I believe the changes for #10 will have at least helped with this. Could you see if it has?

**Comment by martijnrusschen** [comment]
Works for me, thanks!

**Comment by DZittersteyn** [comment]
Yup, that worked! thanks a bundle!

**Comment by gshutler** [comment]
Excellent. The thanks should go to @bmorrall

**Comment by DZittersteyn** [comment]
:+1: @bmorrall!
